# Generated by Django 5.1.1 on 2024-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Accepted', 'Accepted'), ('Check-in', 'Check-in'), ('Check-out', 'Check-out')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='4EF3D56621A5', editable=False, max_length=12),
        ),
    ]
