# Generated by Django 5.1.1 on 2024-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_filter_booking_hotel_alter_booking_booking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='60E42D2D0D0C', editable=False, max_length=12),
        ),
    ]
