# Generated by Django 5.1.1 on 2024-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='AFE26C6BAEE7', editable=False, max_length=12),
        ),
    ]
