# Generated by Django 5.1.1 on 2024-12-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='20241206033541030F798CBE914A', editable=False, max_length=12),
        ),
    ]
